version: '3.1'

services:

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: lottery_db
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - core_service_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - core_service_network

networks:
  core_service_network:
    driver: bridge
    name: core_service_network