version: '3.1'
services:
  app:
    image: maven:3.8.6-openjdk-18-slim
    container_name: domain_app
    working_dir: /app
    volumes:
      - ./:/app
      - lottery_m2_volume:/root/.m2
    depends_on:
      - migrate
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    command:
      - "mvn"
      - "spring-boot:run"

  postgres:
    image: postgres:11-bullseye
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - lottery_data_volume:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    healthcheck:
      test: pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_PASSWORD}
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./CI-CD/database:/database
    command:
      [ "-path", "/database", "-database",  "postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=disable", "up" ]

volumes:
  lottery_m2_volume:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/.m2
      o: bind
  lottery_data_volume:
    driver: local